import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { existsSync, readFileSync } from "fs";
import path from "path";
import { defineConfig } from "vite";

const { version } = JSON.parse(
  readFileSync(path.resolve(__dirname, "../../package.json"), "utf-8"),
);

// Optional locally-trusted HTTPS certs (generated by scripts/ssl-setup.mjs
// into .local/certs). When present, the dev server serves https://decksift.local
// (and https://localhost) — required for Web Serial, which only works in a
// secure context and treats *.local as insecure over plain HTTP.
const CERT_DIR = path.resolve(__dirname, "../../../.local/certs");
const certFile = path.join(CERT_DIR, "decksift.local.pem");
const keyFile = path.join(CERT_DIR, "decksift.local-key.pem");
const hasCerts = existsSync(certFile) && existsSync(keyFile);

export default defineConfig({
  plugins: [react(), tailwindcss()],
  define: {
    __APP_VERSION__: JSON.stringify(`${version}`),
  },
  envDir: path.resolve(__dirname, "../../"),
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  server: {
    host: true, // reachable via localhost, decksift.local, and LAN IPs
    port: 5173,
    ...(hasCerts
      ? {
          https: {
            cert: readFileSync(certFile),
            key: readFileSync(keyFile),
          },
        }
      : {}),
    proxy: {
      // The server serves the API under /api/* (see packages/server/src/
      // index.ts), so this is a pure passthrough — no prefix rewrite.
      "/api": {
        target: "http://localhost:3001",
        changeOrigin: true,
      },
    },
  },
  preview: {
    // Same /api passthrough for the serve-from-dist workflow.
    proxy: {
      "/api": {
        target: "http://localhost:3001",
        changeOrigin: true,
      },
    },
  },
});
